name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Java
        run: |
          mkdir ./.temp
          wget -O ./.temp/jdk.tar.gz https://download.java.net/java/GA/jdk19.0.2/fdb695a9d9064ad6b064dc6df578380c/7/GPL/openjdk-19.0.2_linux-x64_bin.tar.gz
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: jdkfile
          jdkFile: ./.temp/jdk.tar.gz
          java-version: "19.0.2"
          architecture: x64
      - name: Check Java version
        run: java -version
      - name: Download JavaFX
        run: |
          wget -O ./.temp/javafx.zip https://download2.gluonhq.com/openjfx/19.0.2.1/openjfx-19.0.2.1_linux-x64_bin-sdk.zip
      - name: Setup JavaFX
        run: |
          unzip ./.temp/javafx.zip -d ./.temp
          mv ./.temp/javafx-sdk* ./.temp/javafx
          echo "FX_MODULES=javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web" >> $GITHUB_ENV
      - name: Build
        run: javac --module-path ./.temp/javafx --add-modules $FX_MODULES App.java
      - name: Run
        run: |
          java --module-path ./.temp/javafx --add-modules $FX_MODULES App &
          sleep 5
          kill $!
